services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"    # Qdrant REST API & UI
    environment:
      QDRANT__SERVICE__API_KEY: "your-qdrant-api-key"       # Optional, but recommended
    volumes:
      - ./qdrant_data:/qdrant/storage   # Persistent storage

  qdrant-web-ui:
    image: node:20
    container_name: qdrant-web-ui
    working_dir: /ui
    restart: unless-stopped
    command: sh -c "npm install && npm run build && npx serve -s build -l 3000"
    ports:
      - "3000:3000"
    volumes:
      - ./web-ui:/ui
    depends_on:
      - qdrant
    environment:
      # Optional: Set the endpoint for your Qdrant backend
      QDRANT_HOST: "http://qdrant:6333"
