services:
  qdrant:
    image: qdrant/qdrant:latest
    environment:
      QDRANT__SERVICE__API_KEY: ${QDRANT__SERVICE__API_KEY}
    volumes:
      - qdrant_data:/qdrant/storage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qdrant.rule=Host(`qdrant.martin-linde.com`)"
      - "traefik.http.services.qdrant.loadbalancer.server.port=6333"

  qdrant-web-ui:
    build: .
    environment:
      # These will be used by nginx to proxy API calls
      QDRANT_URL: https://qdrant.martin-linde.com
      QDRANT_API_KEY: ${QDRANT__SERVICE__API_KEY}
    depends_on:
      - qdrant
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qdrant-ui.rule=Host(`qdrant-web-ui.martin-linde.com`)"
      - "traefik.http.services.qdrant-ui.loadbalancer.server.port=3000"

volumes:
  qdrant_data:
