services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"  # Enable this for built-in dashboard
    environment:
      QDRANT__SERVICE__API_KEY: ${QDRANT__SERVICE__API_KEY}
    volumes:
      - ./qdrant_data:/qdrant/storage

  qdrant-web-ui:
    image: qdrant/qdrant-web-ui:latest
    ports:
      - "3000:80"
    environment:
      QDRANT_API_URL: http://qdrant:6333
    depends_on:
      - qdrant
