services:
  qdrant:
    image: qdrant/qdrant:latest
    environment:
      QDRANT__SERVICE__API_KEY: ${QDRANT__SERVICE__API_KEY}
    volumes:
      - qdrant_data:/qdrant/storage

  qdrant-web-ui:
    build: .
    environment:
      # The key fix - point to the DATABASE, not the UI
      REACT_APP_QDRANT_URL: https://qdrant.martin-linde.com
      # Also try these if the above doesn't work:
      # VITE_QDRANT_URL: https://qdrant.martin-linde.com
      # QDRANT_API_URL: https://qdrant.martin-linde.com
    depends_on:
      - qdrant

volumes:
  qdrant_data:
