services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    environment:
      QDRANT__SERVICE__API_KEY: ${QDRANT__SERVICE__API_KEY}
    volumes:
      - qdrant_data:/qdrant/storage

  qdrant-web-ui:
    build: .  # This will use your Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_QDRANT_URL: http://qdrant:6333
    depends_on:
      - qdrant

volumes:
  qdrant_data:
